### ISSUE TITLE
Unable to run in self-hosted instances

### ISSUE THREAD

**Issue by ppamorim** [maxim-lobanov/setup-cocoapods#17]
When running in a self-hosted instance of github-actions, I get this error:

<img width="695" alt="Screenshot 2021-08-06 at 11 16 08" src="https://user-images.githubusercontent.com/5521682/128495839-12076607-5818-4c2e-b81e-b56bcefd2a36.png">

Possibly because the self-hosted instance does not have access to `sudo`.

**Comment by HugoGresse** [comment]
Issue is still present :/ 

But you can go around it by seting up ruby first : 

```

            - uses: ruby/setup-ruby@v1
              with:
                  ruby-version: 3.0.0
            -   name: setup-cocoapods
                uses: maxim-lobanov/setup-cocoapods@v1
                with:
                    podfile-path: ios/Podfile.lock

```
