### ISSUE TITLE
Why cannot we specified the cocoapod version at the same time as the podfile-path? 

### ISSUE THREAD

**Issue by HugoGresse** [maxim-lobanov/setup-cocoapods#30]
Due to [an issue when building React Native apps with cocoapods 1.15 released last week](https://github.com/facebook/react-native/issues/42698) I need to rollback the cocoapod version installed, which I cannot do because this fine action don't allow the two parameters to be used at the same time: 

```
           ## selfhosted instance with pod --version = 1.14.3
            - uses: ruby/setup-ruby@v1
              with:
                  ruby-version: 3.0.0
            -   name: setup-cocoapods
                uses: maxim-lobanov/setup-cocoapods@v1
                with:
                    podfile-path: ios/Podfile.lock
                    version: 1.14.3
```

here is the stack of the error : 
```
   CocoaPods : 1.15.0
        Ruby : ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [arm64-darwin22]
    RubyGems : 3.2.3
        Host : macOS 13.6.3 (22G436)
       Xcode : 15.2 (15C500b)
         Git : git version 2.39.3 (Apple Git-145)
Ruby lib dir : /Users/runner/hostedtoolcache/Ruby/3.0.0/arm64/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

the cocoapod version is changed unfortunately :/
